/* Automatically generated by configure - do not modify */
#ifndef CONFIG_TCCDIR
# define CONFIG_TCCDIR "/usr/local/lib/tcc"
#endif
#ifndef CONFIG_TCC_PREDEFS
# define CONFIG_TCC_PREDEFS 1
#endif
#define TCC_VERSION "0.9.27"
#define TCC_MAJOR 0
#define TCC_MINOR 927
#define CC_NAME CC_tcc
